In [1]:
import pandas as pd

# Let's create some Pandas Series and Dataframes! 
In this notebook we will see how to create and access pandas series and dataframes.

## Exercise 1 - Create and access a Pandas Series
Create a pandas series with:
 - the following values:  [1, 3, 2, 7, 5, 4, 9] 
 - indexed with the following fruit names: ["apple", "orange", "cherry", "pear", "pineapple", "mango", "banana"]

Then print:
 - the first three elements of the series
 - all the values associated to a "pear" or a "mango"
 - all the indexes associated to a value greater than 5

In [2]:
s = pd.Series([1, 3, 2, 7, 5, 4, 9], index=["apple", "orange", "cherry", "pear", "pineapple", "mango", "banana"])

s.iloc[:3]

apple     1
orange    3
cherry    2
dtype: int64

In [3]:
s.loc[["pear", "mango"]]

pear     7
mango    4
dtype: int64

In [9]:
s.loc[s > 5].index

Index(['pear', 'banana'], dtype='str')

## Exercise 2 - Create and access a Pandas Dataframe
Given the following input table with 13 samples and 4 attributes:

```
[[5.1, 3.5, 1, 0.2],
[4.3, 3. , 1, 0.1],
[5. , 0. , 1, 0.4],
[5.1, 3.4, 2, 0.2],
[7.0, 3.2, 1, 0.2],
[6.9, 3.1, 3, 1.5],
[6.7, 3.1, 1, 2. ],
[6. , 2.9, 2, 1.5],
[6.1, 3. , 2, 1.4],
[6.5, 3. , 3, 2.2],
[7.7, 3.8, 3, 2.2],
[7.4, 2.8, 1, 1.9],
[6.8, 3.2, 1, 2.3]]
```

Given the following column names
['height','width','intensity','weight']

Compute the following:
- Create a pandas dataframe with the given data and column names
- Add a new composite feature, 'area' = 'width' * 'height'
- Retrieve the elements associated to an odd index
- Retrieve the 'height' and 'weight' of the samples with area > 20

In [5]:
df = pd.DataFrame([[5.1, 3.5, 1, 0.2],
[4.3, 3. , 1, 0.1],
[5. , 0. , 1, 0.4],
[5.1, 3.4, 2, 0.2],
[7.0, 3.2, 1, 0.2],
[6.9, 3.1, 3, 1.5],
[6.7, 3.1, 1, 2. ],
[6. , 2.9, 2, 1.5],
[6.1, 3. , 2, 1.4],
[6.5, 3. , 3, 2.2],
[7.7, 3.8, 3, 2.2],
[7.4, 2.8, 1, 1.9],
[6.8, 3.2, 1, 2.3]], columns=['height','width','intensity','weight'])

df

    height  width  intensity  weight
0      5.1    3.5          1     0.2
1      4.3    3.0          1     0.1
2      5.0    0.0          1     0.4
3      5.1    3.4          2     0.2
4      7.0    3.2          1     0.2
5      6.9    3.1          3     1.5
6      6.7    3.1          1     2.0
7      6.0    2.9          2     1.5
8      6.1    3.0          2     1.4
9      6.5    3.0          3     2.2
10     7.7    3.8          3     2.2
11     7.4    2.8          1     1.9
12     6.8    3.2          1     2.3

In [6]:
df["area"] = df["width"] * df["height"]
df

    height  width  intensity  weight   area
0      5.1    3.5          1     0.2  17.85
1      4.3    3.0          1     0.1  12.90
2      5.0    0.0          1     0.4   0.00
3      5.1    3.4          2     0.2  17.34
4      7.0    3.2          1     0.2  22.40
5      6.9    3.1          3     1.5  21.39
6      6.7    3.1          1     2.0  20.77
7      6.0    2.9          2     1.5  17.40
8      6.1    3.0          2     1.4  18.30
9      6.5    3.0          3     2.2  19.50
10     7.7    3.8          3     2.2  29.26
11     7.4    2.8          1     1.9  20.72
12     6.8    3.2          1     2.3  21.76

In [7]:
df.iloc[0:len(df):2]

    height  width  intensity  weight   area
0      5.1    3.5          1     0.2  17.85
2      5.0    0.0          1     0.4   0.00
4      7.0    3.2          1     0.2  22.40
6      6.7    3.1          1     2.0  20.77
8      6.1    3.0          2     1.4  18.30
10     7.7    3.8          3     2.2  29.26
12     6.8    3.2          1     2.3  21.76

In [8]:
df.loc[df["area"] > 20][["height", "weight"]]

    height  weight
4      7.0     0.2
5      6.9     1.5
6      6.7     2.0
10     7.7     2.2
11     7.4     1.9
12     6.8     2.3